var cityData = [
  {
    "State":"New Mexico",
    "City":"Albuquerque",
    "Population":558874,
    "ViolentCrime":882.8
  },
  {
    "State":"California",
    "City":"Anaheim",
    "Population":346956,
    "ViolentCrime":317.3
  },
  {
    "State":"Alaska",
    "City":"Anchorage",
    "Population":301306,
    "ViolentCrime":864.6
  },
  {
    "State":"Texas",
    "City":"Arlington",
    "Population":382976,
    "ViolentCrime":484.1
  },
  {
    "State":"Georgia",
    "City":"Atlanta",
    "Population":454363,
    "ViolentCrime":1227.40
  },
  {
    "State":"Colorado",
    "City":"Aurora",
    "Population":350948,
    "ViolentCrime":412.6
  },
  {
    "State":"Texas",
    "City":"Austin",
    "Population":903924,
    "ViolentCrime":396.2
  },
  {
    "State":"California",
    "City":"Bakersfield",
    "Population":367406,
    "ViolentCrime":456.7
  },
  {
    "State":"Maryland",
    "City":"Baltimore",
    "Population":623513,
    "ViolentCrime":1338.50
  },
  {
    "State":"Massachusetts",
    "City":"Boston",
    "Population":654413,
    "ViolentCrime":725.7
  },
  {
    "State":"New York",
    "City":"Buffalo",
    "Population":258419,
    "ViolentCrime":1228.20
  },
  {
    "State":"Arizona",
    "City":"Chandler",
    "Population":252369,
    "ViolentCrime":184.7
  },
  {
    "State":"North Carolina",
    "City":"Charlotte-Mecklenburg",
    "Population":856916,
    "ViolentCrime":589.8
  },
  {
    "State":"California",
    "City":"Chula Vista",
    "Population":259894,
    "ViolentCrime":235.5
  },
  {
    "State":"Illinois",
    "City":"Chicago",
    "Population":2724121,
    "ViolentCrime":884.3
  },
  {
    "State":"Ohio",
    "City":"Cincinnati",
    "Population":297671,
    "ViolentCrime":905.4
  },
  {
    "State":"Ohio",
    "City":"Cleveland",
    "Population":388655,
    "ViolentCrime":1334.30
  },
  {
    "State":"Colorado",
    "City":"Colorado Springs",
    "Population":444949,
    "ViolentCrime":458.3
  },
  {
    "State":"Ohio",
    "City":"Columbus",
    "Population":830811,
    "ViolentCrime":549.2
  },
  {
    "State":"Texas",
    "City":"Corpus Christi",
    "Population":319211,
    "ViolentCrime":656
  },
  {
    "State":"Texas",
    "City":"Dallas",
    "Population":1272396,
    "ViolentCrime":664.7
  },
  {
    "State":"Colorado",
    "City":"Denver",
    "Population":665353,
    "ViolentCrime":598.6
  },
  {
    "State":"Michigan",
    "City":"Detroit",
    "Population":684694,
    "ViolentCrime":1988.60
  },
  {
    "State":"Texas",
    "City":"El Paso",
    "Population":680273,
    "ViolentCrime":392.6
  },
  {
    "State":"Indiana",
    "City":"Fort Wayne",
    "Population":257172,
    "ViolentCrime":317.3
  },
  {
    "State":"Texas",
    "City":"Fort Worth*",
    "Population":789035,
    "ViolentCrime":560.2
  },
  {
    "State":"California",
    "City":"Fresno",
    "Population":513187,
    "ViolentCrime":464.2
  },
  {
    "State":"North Carolina",
    "City":"Greensboro",
    "Population":282203,
    "ViolentCrime":477
  },
  {
    "State":"Nevada",
    "City":"Henderson",
    "Population":274121,
    "ViolentCrime":164.9
  },
  {
    "State":"Texas",
    "City":"Houston",
    "Population":2219933,
    "ViolentCrime":991.4
  },
  {
    "State":"Indiana",
    "City":"Indianapolis",
    "Population":858238,
    "ViolentCrime":1254.70
  },
  {
    "State":"Florida",
    "City":"Jacksonville",
    "Population":856021,
    "ViolentCrime":683.7
  },
  {
    "State":"New Jersey",
    "City":"Jersey City",
    "Population":260005,
    "ViolentCrime":531.1
  },
  {
    "State":"Missouri",
    "City":"Kansas City",
    "Population":468417,
    "ViolentCrime":1251.40
  },
  {
    "State":"Texas",
    "City":"Laredo",
    "Population":250994,
    "ViolentCrime":388.9
  },
  {
    "State":"Nevada",
    "City":"Las Vegas",
    "Population":1530899,
    "ViolentCrime":841.1
  },
  {
    "State":"Kentucky",
    "City":"Lexington",
    "Population":311848,
    "ViolentCrime":333.8
  },
  {
    "State":"Nebraska",
    "City":"Lincoln",
    "Population":271208,
    "ViolentCrime":338.5
  },
  {
    "State":"California",
    "City":"Long Beach",
    "Population":471123,
    "ViolentCrime":489
  },
  {
    "State":"California",
    "City":"Los Angeles",
    "Population":3906772,
    "ViolentCrime":490.7
  },
  {
    "State":"Kentucky",
    "City":"Louisville Metro",
    "Population":677710,
    "ViolentCrime":591
  },
  {
    "State":"Tennessee",
    "City":"Memphis",
    "Population":654922,
    "ViolentCrime":1740.50
  },
  {
    "State":"Arizona",
    "City":"Mesa",
    "Population":462092,
    "ViolentCrime":458.6
  },
  {
    "State":"Florida",
    "City":"Miami",
    "Population":421996,
    "ViolentCrime":1060.00
  },
  {
    "State":"Wisconsin",
    "City":"Milwaukee",
    "Population":600374,
    "ViolentCrime":1476.40
  },
  {
    "State":"Minnesota",
    "City":"Minneapolis",
    "Population":404461,
    "ViolentCrime":1012.00
  },
  {
    "State":"Alabama",
    "City":"Mobile",
    "Population":250655,
    "ViolentCrime":593.6
  },
  {
    "State":"Tennessee",
    "City":"Nashville",
    "Population":647689,
    "ViolentCrime":1122.50
  },
  {
    "State":"Louisiana",
    "City":"New Orleans",
    "Population":387113,
    "ViolentCrime":973.9
  },
  {
    "State":"New York",
    "City":"New York",
    "Population":8473938,
    "ViolentCrime":596.7
  },
  {
    "State":"New Jersey",
    "City":"Newark",
    "Population":279110,
    "ViolentCrime":1077.70
  },
  {
    "State":"California",
    "City":"Oakland",
    "Population":409994,
    "ViolentCrime":1685.40
  },
  {
    "State":"Oklahoma",
    "City":"Oklahoma City",
    "Population":617975,
    "ViolentCrime":773.8
  },
  {
    "State":"Nebraska",
    "City":"Omaha",
    "Population":438465,
    "ViolentCrime":560.6
  },
  {
    "State":"Florida",
    "City":"Orlando",
    "Population":259675,
    "ViolentCrime":901.1
  },
  {
    "State":"Pennsylvania",
    "City":"Philadelphia",
    "Population":1559062,
    "ViolentCrime":1021.40
  },
  {
    "State":"Arizona",
    "City":"Phoenix",
    "Population":1529852,
    "ViolentCrime":571.9
  },
  {
    "State":"Pennsylvania",
    "City":"Pittsburgh",
    "Population":307613,
    "ViolentCrime":798.1
  },
  {
    "State":"Texas",
    "City":"Plano",
    "Population":277822,
    "ViolentCrime":165.2
  },
  {
    "State":"Oregon",
    "City":"Portland",
    "Population":615672,
    "ViolentCrime":472.8
  },
  {
    "State":"North Carolina",
    "City":"Raleigh*",
    "Population":428993,
    "ViolentCrime":392.3
  },
  {
    "State":"California",
    "City":"Riverside",
    "Population":319453,
    "ViolentCrime":433.2
  },
  {
    "State":"California",
    "City":"Sacramento",
    "Population":482767,
    "ViolentCrime":614.8
  },
  {
    "State":"Texas",
    "City":"San Antonio",
    "Population":1428465,
    "ViolentCrime":539.3
  },
  {
    "State":"California",
    "City":"San Diego",
    "Population":1368690,
    "ViolentCrime":380.9
  },
  {
    "State":"California",
    "City":"San Francisco",
    "Population":850294,
    "ViolentCrime":795.1
  },
  {
    "State":"California",
    "City":"San Jose",
    "Population":1009679,
    "ViolentCrime":321.1
  },
  {
    "State":"California",
    "City":"Santa Ana",
    "Population":336462,
    "ViolentCrime":374.5
  },
  {
    "State":"Washington",
    "City":"Seattle",
    "Population":663410,
    "ViolentCrime":603.1
  },
  {
    "State":"Missouri",
    "City":"St. Louis",
    "Population":318574,
    "ViolentCrime":1678.70
  },
  {
    "State":"Minnesota",
    "City":"St. Paul",
    "Population":297984,
    "ViolentCrime":662.5
  },
  {
    "State":"Florida",
    "City":"St. Petersburg",
    "Population":250772,
    "ViolentCrime":864.9
  },
  {
    "State":"California",
    "City":"Stockton",
    "Population":299519,
    "ViolentCrime":1331.50
  },
  {
    "State":"Florida",
    "City":"Tampa",
    "Population":357124,
    "ViolentCrime":582.4
  },
  {
    "State":"Ohio",
    "City":"Toledo",
    "Population":281150,
    "ViolentCrime":1091.20
  },
  {
    "State":"Arizona",
    "City":"Tucson",
    "Population":525486,
    "ViolentCrime":640.9
  },
  {
    "State":"Oklahoma",
    "City":"Tulsa",
    "Population":399556,
    "ViolentCrime":805.1
  },
  {
    "State":"Virginia",
    "City":"Virginia Beach",
    "Population":451102,
    "ViolentCrime":146.3
  },
  {
    "State":"District of Columbia",
    "City":"Washington",
    "Population":658893,
    "ViolentCrime":1185.3
  },
  {
    "State":"Kansas",
    "City":"Wichita",
    "Population":386486,
    "ViolentCrime":793.0
  }
  ];