var data = [
  
  "B.J. Thomas",
  "B.J. Thomas",
  "B.J. Thomas",
  "B.J. Thomas",
  "Jackson 5",
  "The Shocking Blue",
  "Sly & The Family Stone",
  "Sly & The Family Stone",
  "Simon & Garfunkel",
  "Simon & Garfunkel",
  "Simon & Garfunkel",
  "Simon & Garfunkel",
  "Simon & Garfunkel",
  "Simon & Garfunkel",
  "The Beatles",
  "The Beatles",
  "Jackson 5",
  "Jackson 5",
  "The Guess Who",
  "The Guess Who",
  "The Guess Who",
  "Ray Stevens",
  "Ray Stevens",
  "The Beatles",
  "The Beatles",
  "Jackson 5",
  "Jackson 5",
  "Three Dog Night",
  "Three Dog Night",
  "Carpenters",
  "Carpenters",
  "Carpenters",
  "Carpenters",
  "Edwin Starr",
  "Edwin Starr",
  "Edwin Starr",
  "Diana Ross",
  "Diana Ross",
  "Diana Ross",
  "Neil Diamond",
  "Jackson 5",
  "Jackson 5",
  "Jackson 5",
  "Jackson 5",
  "Jackson 5",
  "The Patridge Family Starring Shirley Jones Featuring David Cassidy",
  "The Patridge Family Starring Shirley Jones Featuring David Cassidy",
  "The Patridge Family Starring Shirley Jones Featuring David Cassidy",
  "Smokey Robinson & The Miracles",
  "Smokey Robinson & The Miracles",
  "George Harrison",
    "George Harrison",
    "George Harrison",
    "George Harrison",
    "Dawn",
    "Dawn",
    "Dawn",
    "The Osmonds",
    "The Osmonds",
    "The Osmonds",
    "The Osmonds",
    "The Osmonds",
    "Janis Joplin",
    "Janis Joplin",
    "The Temptations",
    "The Temptations",
    "Three Dog Night",
    "Three Dog Night",
    "Three Dog Night",
    "Three Dog Night",
    "Three Dog Night",
    "Three Dog Night",
    "The Rolling Stones",
    "The Rolling Stones",
    "The Honey Cone",
    "Carole King",
    "Carole King",
    "Carole King",
    "Carole King",
    "Carole King",
    "James Taylor",
    "Bee Gees",
    "Bee Gees",
    "Bee Gees",
    "Bee Gees",
    "Paul & Linda McCartney",
    "Donny Osmond",
    "Donny Osmond",
    "Donny Osmond",
    "Rod Stewart",
    "Rod Stewart",
    "Rod Stewart",
    "Rod Stewart",
    "Rod Stewart",
    "Cher",
    "Cher",
    "Isaac Hayes",
    "Isaac Hayes",
    "Sly & The Family Stone",
    "Sly & The Family Stone",
    "Sly & The Family Stone",
    "Melanie",
   "Melanie",
   "Melanie",
   "Don McLean",
   "Don McLean",
   "Don McLean",
   "Don McLean",
   "Al Green",
   "Nilsson",
   "Nilsson",
   "Nilsson",
   "Nilsson",
   "Neil Young",
   "America",
   "America",
   "America",
   "Roberta Flack",
   "Roberta Flack",
   "Roberta Flack",
    "Roberta Flack",
    "Roberta Flack",
    "Roberta Flack",
    "The Chi-lites",
   "The Staple Singers",
   "Sammy Davis, Jr. with The Mike Curb Congregation",
   "Sammy Davis, Jr. with The Mike Curb Congregation",
   "Sammy Davis, Jr. with The Mike Curb Congregation",
   "Neil Diamond",
   "Bill Withers",
   "Bill Withers",
   "Bill Withers",
   "Gilbert O'Sullivan",
   "Gilbert O'Sullivan",
   "Gilbert O'Sullivan",
   "Gilbert O'Sullivan",
   "Looking Glass",
   "Gilbert O'Sullivan",
   "Gilbert O'Sullivan",
   "Three Dog Night",
   "Mac Davis",
   "Mac Davis",
   "Mac Davis",
   "Michael Jackson",
   "Chuck Berry",
   "Chuck Berry",
   "Johnny Nash",
   "Johnny Nash",
   "Johnny Nash",
   "Johnny Nash",
   "The Temptations",
   "Helen Reddy",
   "Billy Paul",
   "Billy Paul",
   "Billy Paul",
   "Carly Simon",
   "Carly Simon",
   "Carly Simon",
   "Stevie Wonder",
   "Elton John",
   "Elton John",
   "Elton John",
   "Roberta Flack",
   "Roberta Flack",
   "Roberta Flack",
   "Roberta Flack",
   "The O'Jays",
   "Roberta Flack",
   "Vicki Lawrence",
   "Vicki Lawrence",
   "Dawn Featuring Tony Orlando",
   "Dawn Featuring Tony Orlando",
   "Dawn Featuring Tony Orlando",
   "Dawn Featuring Tony Orlando",
   "Stevie Wonder",
   "Edgar Winter Group",
   "Paul McCartney & Wings",
   "Paul McCartney & Wings",
   "Paul McCartney & Wings",
   "Paul McCartney & Wings",
   "George Harrison",
   "Billy Preston",
   "Billy Preston",
   "Jim Croce",
   "Jim Croce",
   "Maureen McGovern",
   "Maureen McGovern",
   "Diana Ross",
   "Stories",
   "Stories",
   "Marvin Gaye",
   "Helen Reddy",
   "Marvin Gaye",
   "Grand Funk",
   "Cher",
   "Cher",
   "The Rolling Stones",
   "Gladys Knight And The Pips",
   "Gladys Knight And The Pips",
   "Eddie Kendricks",
   "Eddie Kendricks",
   "Ringo Starr",
   "Carpenters",
   "Carpenters",
   "Charlie Rich",
   "Charlie Rich",
   "Jim Croce",
  "Jim Croce",
  "The Steve Miller Band",
  "Al Wilson",
  "Ringo Starr",
  "Barbra Streisand",
  "Love Unlimited Orchestra",
  "Barbra Streisand",
  "Barbra Streisand",
  "Terry Jackson",
  "Terry Jackson",
  "Terry Jackson",
  "Cher",
  "John Denver",
  "Blue Swede",
  "Elton John",
  "MFSB featuring The Three Degrees",
  "MFSB featuring The Three Degrees",
  "Grand Funk",
  "Grand Funk",
  "Ray Stevens",
  "Ray Stevens",
  "Ray Stevens",
  "Paul McCartney & The Wings",
  "Bo Donaldson And The Heywoods",
  "Bo Donaldson And The Heywoods",
  "Gordon lightfoot",
  "The Hues Corporation",
  "George McCrae",
  "George McCrae",
  "John Denver",
  "John Denver",
  "John Denver",
  "Paper Lace",
  "Paul Anka with Odia Coates",
  "Paul Anka with Odia Coates",
  "Paul Anka with Odia Coates",
  "Eric Clapton",
  "Barry White",
  "Andy Kim",
  "Olivia Newton-John",
  "Olivia Newton-John",
  "Billy Preston",
  "Dionne Warwicke & Spinners",
  "Stevie Wonder",
  "Bachman-Turner Overdrive",
  "John Lennon With The Plastic Ono Nuclear Band",
  "Billy Swan",
  "Billy Swan",
  "Carl Douglas",
  "Carl Douglas",
  "Harry Chapin",
  "Helen Reddy",
   "Elton John",
  "Elton John",
  "Barry Manilow",
  "Carpenters",
  "Neil Sedaka",
  "Ohio Players",
  "Linda Ronstadt",
  "AWB",
  "Eagles",
  "Olivia Newton-John",
  "The Doobie Brothers",
  "Frakie Vallie",
  "Labelle",
  "Minnie Riperton",
  "The Elton John Band",
  "The Elton John Band",
  "B.J. Thomas",
  "Tony Orlando & Dawn",
  "Tony Orlando & Dawn",
  "Tony Orlando & Dawn",
  "Earth, Wind & Fire",
  "Freddy Fender",
  "John Denver",
  "America",
  "Captain & Tennille",
  "Captain & Tennille",
  "Captain & Tennille",
  "Captain & Tennille",
  "Wings",
  "Van McCoy The Soul City Symphony",
  "Eagles",
  "Bee Gees",
  "Bee Gees",
  "Hamilton, Joe Frank & Reynolds",
  "KC And The Sunshine Band",
  "Glen Campbell",
  "Glen Campbell",
  "David Bowie",
  "John Denver",
  "David Bowie",
  "Neil Sedaka",
  "Neil Sedaka",
  "Neil Sedaka",
  "Elton John",
  "Elton John",
  "Elton John",
  "KC And The Sunshine Band",
  "Silver Convention",
  "Silver Convention",
  "Silver Convention",
  "KC And The Sunshine Band",
  "The Staple Singers",
   "Bay City Rollers",
  "C.W. McCall",
  "Barry Manilow",
  "Diana Ross",
  "Ohio Players",
  "Paul Simon",
  "Paul Simon",
  "Paul Simon",
  "Rhythm Heritage",
  "The Miracles",
  "The 4 Seasons",
  "The 4 Seasons",
  "The 4 Seasons",
  "Johnnie Taylor",
  "Johnnie Taylor",
  "Johnnie Taylor",
  "Johnnie Taylor",
  "Bellamy Brothers",
  "John Sebastian",
  "The Sylvers",
  "Wings",
  "Diana Ross",
  "Diana Ross",
  "Wings",
  "Wings",
  "Wings",
  "Wings",
  "Starland Vocal Band",
  "Starland Vocal Band",
  "The Manhattans",
  "The Manhattans",
  "Elton John & Kiki Dee",
  "Elton John & Kiki Dee",
  "Elton John & Kiki Dee",
  "Elton John & Kiki Dee",
  "Bee Gees",
  "KC And The Sunshine Band",
  "Wild Cherry",
  "Wild Cherry",
  "Wild Cherry",
  "Walter Murphy & The Big Apple Band",
  "Rick Dees & His Cast Of Idiots",
  "Chicago",
  "Chicago",
  "Steve Miller",
  "Rod Stewart",
  "Rod Stewart",
  "Rod Stewart",
  "Rod Stewart",
  "Rod Stewart",
  "Rod Stewart",
  "Rod Stewart",
   "Rod Stewart",
  "Marilyn McCoo & Billy Davis, Jr.",
  "Leo Sayer",
  "Stevie Wonder",
  "Rose Royce",
  "Mary Macgregor",
  "Mary Macgregor",
  "Manfred Mann's Earth Band",
  "Eagles",
  "Barbra Streisand",
  "Barbra Streisand",
  "Barbra Streisand",
  "Daryl Hall John Oates",
  "Daryl Hall John Oates",
  "ABBA",
  "David Soul",
  "Thelma Houston",
  "Glen Campbell",
  "Eagles",
  "Leo Slayer",
  "Stevie Wonder",
  "Stevie Wonder",
  "Stevie Wonder",
  "KC And The Sunshine Band",
  "Fleetwood Mac",
  "Marvin Gaye",
  "Bill Conti",
  "Alan O'Day",
  "Shaun Cassidy",
  "Barry Manilow",
  "Andy Gibb",
  "Andy Gibb",
  "Andy Gibb",
  "The Emotions",
  "The Emotions",
  "The Emotions",
  "The Emotions",
  "Andy Gibb",
  "The Emotions",
  "Meco",
  "Meco",
  "Debby Boone",
  "Debby Boone",
  "Debby Boone",
  "Debby Boone",
  "Debby Boone",
  "Debby Boone",
  "Debby Boone",
  "Debby Boone",
  "Debby Boone",
  "Debby Boone",
  "Bee Gees",
  "Bee Gees",
   "Bee Gees",
  "Player",
  "Player",
  "Player",
  "Bee Gees",
  "Bee Gees",
  "Bee Gees",
  "Bee Gees",
  "Andy Gibb",
  "Andy Gibb",
  "Bee Gees",
  "Bee Gees",
  "Bee Gees",
  "Bee Gees",
  "Bee Gees",
  "Bee Gees",
  "Bee Gees",
  "Bee Gees",
  "Yvonne Elliman",
  "Wings",
  "Wings",
  "Johnny Mathis/Deniece Williams",
  "John Travolta & Olivia Newton-John",
  "Andy Gibb",
  "Andy Gibb",
  "Andy Gibb",
  "Andy Gibb",
  "Andy Gibb",
  "Andy Gibb",
  "Andy Gibb",
  "The Rolling Stones",
  "Commodores",
  "Commodores",
  "Frankie Valli",
  "Frankie Valli",
  "A Taste Of Honey",
  "A Taste Of Honey",
  "A Taste Of Honey",
  "Exile",
  "Exile",
  "Exile",
  "Exile",
  "Nick Gilder",
  "Anne Murray",
  "Donna Summer",
  "Donna Summer",
  "Donna Summer",
  "Barbra Streisand & Neil Diamond",
  "Chic",
  "Barbra Streisand & Neil Diamond",
  "Chic",
  "Chic",
   "Bee Gees",
  "Bee Gees",
  "Chic",
  "Chic",
  "Chic",
  "Rod Stewart",
  "Rod Stewart",
  "Rod Stewart",
  "Rod Stewart",
  "Gloria Gaynor",
  "Gloria Gaynor",
  "Bee Gees",
  "Bee Gees",
  "Gloria Gaynor",
  "The Doobie Brothers",
  "Amii Stewart",
  "Blondie",
  "Peaches & Herb",
  "Peaches & Herb",
  "Peaches & Herb",
  "Peaches & Herb",
  "Donna Summer",
  "Bee Gees",
  "Donna Summer",
  "Donna Summer",
  "Anita Ward",
  "Anita Ward",
  "Donna Summer",
  "Donna Summer",
  "Donna Summer",
  "Donna Summer",
  "Donna Summer",
  "Chic",
  "The Knack",
  "The Knack",
  "The Knack",
  "The Knack",
  "The Knack",
  "The Knack",
  "Robert John",
  "Michael Jackson",
  "Herb Alpert",
  "Herb Alpert",
  "M",
  "Eagles",
  "Commodores",
  "Barbra Streisand/Donna Summer",
  "Barbra Streisand/Donna Summer",
  "Styx",
  "Styx",
  "Rupert Holmes",
  "Rupert Holmes",


  "KC And The Sunshine Band",
  "Rupert Holmes",
  "Michael Jackson",
  "Michael Jackson",
  "Michael Jackson",
  "Michael Jackson",
  "Captain & Tennille",
  "Queen",
  "Queen",
  "Queen",
  "Queen",
  "Pink Floyd",
  "Pink Floyd",
  "Pink Floyd",
  "Pink Floyd",
  "Blondie",
  "Blondie",
  "Blondie",
  "Blondie",
  "Blondie",
  "Blondie",
  "Lipps, Inc.",
  "Lipps, Inc.",
  "Lipps, Inc.",
  "Lipps, Inc.",
  "Paul McCartney & Wings",
  "Paul McCartney & Wings",
  "Paul McCartney & Wings",
  "Billy Joel",
  "Billy Joel",
  "Olivia Newton-John",
  "Olivia Newton-John",
  "Olivia Newton-John",
  "Olivia Newton-John",
  "Christopher Cross",
  "Diana Ross",
  "Diana Ross",
  "Diana Ross",
  "Diana Ross",
  "Queen",
  "Queen",
  "Queen",
  "Barbra Streisand",
  "Barbra Streisand",
  "Barbra Streisand",
  "Kenny Rogers",
  "Kenny Rogers",
  "Kenny Rogers",
  "Kenny Rogers",
  "Kenny Rogers",
  "Kenny Rogers",
  "John Lennon",


  "John Lennon",
  "John Lennon",
  "John Lennon",
  "John Lennon",
  "Blondie",
  "Kool & The Gang",
  "Kool & The Gang",
  "Dolly Parton",
  "Eddie Rabbitt",
  "Eddie Rabbitt",
  "Dolly Parton",
  "REO Speedwagon",
  "Blondie",
  "Blondie",
  "Daryl Hall John Oates",
  "Daryl Hall John Oates",
  "Daryl Hall John Oates",
  "Sheena Easton",
  "Sheena Easton",
  "Kim Carnes",
  "Kim Carnes",
  "Kim Carnes",
  "Kim Carnes",
  "Kim Carnes",
  "Stars On 45",
  "Kim Carnes",
  "Kim Carnes",
  "Kim Carnes",
  "Kim Carnes",
  "Air Supply",
  "Rick Springfield",
  "Rick Springfield",
  "Diana Ross & Lionel Richie",
  "Diana Ross & Lionel Richie",
  "Diana Ross & Lionel Richie",
  "Diana Ross & Lionel Richie",
  "Diana Ross & Lionel Richie",
  "Diana Ross & Lionel Richie",
  "Diana Ross & Lionel Richie",
  "Diana Ross & Lionel Richie",
  "Diana Ross & Lionel Richie",
  "Christopher Cross",
  "Christopher Cross",
  "Christopher Cross",
  "Daryl Hall John Oates",
  "Daryl Hall John Oates",
  "Olivia Newton-John",
  "Olivia Newton-John",
  "Olivia Newton-John",
  "Olivia Newton-John",
  "Olivia Newton-John",
  "Olivia Newton-John",


  "Olivia Newton-John",
  "Olivia Newton-John",
  "Olivia Newton-John",
  "Olivia Newton-John",
  "Daryl Hall John Oates",
  "The J. Geils Band",
  "The J. Geils Band",
  "The J. Geils Band",
  "The J. Geils Band",
  "The J. Geils Band",
  "The J. Geils Band",
  "Joan Jett And The Blackhearts",
  "Joan Jett And The Blackhearts",
  "Joan Jett And The Blackhearts",
  "Joan Jett And The Blackhearts",
  "Joan Jett And The Blackhearts",
  "Joan Jett And The Blackhearts",
  "Joan Jett And The Blackhearts",
  "Vangelis",
  "Paul McCartney And Stevie Wonder",
  "Paul McCartney And Stevie Wonder",
  "Paul McCartney And Stevie Wonder",
  "Paul McCartney And Stevie Wonder",
  "Paul McCartney And Stevie Wonder",
  "Paul McCartney And Stevie Wonder",
  "Paul McCartney And Stevie Wonder",
  "The Human League",
  "The Human League",
  "The Human League",
  "Survivor",
  "Survivor",
  "Survivor",
  "Survivor",
  "Survivor",
  "Survivor",
  "The Steve Miller Band",
  "Chicago",
  "Chicago",
  "The Steve Miller Band",
  "John Cougar",
  "John Cougar",
  "John Cougar",
  "John Cougar",
  "Men At Work",
  "Joe Cocker And Jennifer Warnes",
  "Joe Cocker And Jennifer Warnes",
  "Joe Cocker And Jennifer Warnes",
  "Lionel Richie",
  "Lionel Richie",
  "Toni Basil",
  "Daryl Hall John Oates",
  "Daryl Hall John Oates",


  "Daryl Hall John Oates",
  "Daryl Hall John Oates",
  "Men At Work",
  "Men At Work",
  "Men At Work",
  "Toto",
  "Men At Work",
  "Patti Austin",
  "Patti Austin",
  "Michael Jackson",
  "Michael Jackson",
  "Michael Jackson",
  "Michael Jackson",
  "Michael Jackson",
  "Michael Jackson",
  "Michael Jackson",
  "Dexys Midnight Runners",
  "JMichael Jackson",
  "Michael Jackson",
  "Michael Jackson",
  "David Bowie",
  "Irene Cara",
  "Irene Carar",
  "Irene Cara",
  "Irene Cara",
  "Irene Cara",
  "Irene Cara",
  "The Police",
  "The Police",
  "The Police",
  "The Police",
  "The Police",
  "The Police",
  "The Police",
  "The Police",
  "Eurythmics",
  "Michael Sembello",
  "Michael Sembello",
  "Billy Joel",
  "Bonnie Tyler",
  "Bonnie Tyler",
  "Bonnie Tyler",
  "Bonnie Tyler",
  "Kenny Rogers",
  "Kenny Rogers",
  "Lionel Richie",
  "Lionel Richie",
  "Lionel Richie",
  "Lionel Richie",
  "Paul McCartney And Michael Jackson",
  "Paul McCartney And Michael Jackson",
  "Paul McCartney And Michael Jackson",
  "Paul McCartney And Michael Jackson" ,


  "Paul McCartney And Michael Jackson" ,
  "Paul McCartney And Michael Jackson" ,
  "Yes",
  "Yes",
  "Culture Club",
  "Culture Club",
  "Culture Club",
  "Van Halen",
  "Van Halen",
  "Van Halen",
  "Van Halen",
  "Van Halen",
  "Kenny Loggins" ,
  "Kenny Loggins",
  "Kenny Loggins",
  "Phil Collins",
  "Phil Collins",
  "Phil Collins",
  "Lionel Richie",
  "Lionel Richie",
  "Deniece Williams",
  "Deniece Williams",
  "Cyndi Lauper",
  "Cyndi Lauper",
  "Duran Duran",
  "Duran Duran",
  "Prince",
  "Prince",
  "Prince",
  "Prince",
  "Prince",
  "Ray Parker Jr.",
  "Ray Parker Jr.",
  "Ray Parker Jr.",
  "Tina Turner",
  "Tina Turner",
  "Tina Turner",
  "John Waite",
  "Prince",
  "Prince",
  "Stevie Wonder",
  "Stevie Wonder",
  "Stevie Wonder",
  "Billy Ocean",
  "Billy Ocean",
  "Wham!",
  "Wham!",
  "Wham!",
  "Daryl Hall John Oates",
  "Daryl Hall John Oates",
  "Madonna",
  "Madonna" ,


  "Madonna" ,
  "Madonna" ,
  "Madonna",
  "Madonna",
  "Foreigner",
  "Foreigner",
  "Wham!",
  "Wham!",
  "Wham!",
  "REO Speedwagon",
  "REO Speedwagon",
  "REO Speedwagon",
  "Phil Collins" ,
  "Phil Collins",
  "USA For Africa",
  "USA For Africa",
  "USA For Africa",
  "USA For Africa",
  "Madonna",
  "Simple Minds",
  "Wham!",
  "Wham!",
  "Tears For Fears",
  "Tears For Fears",
  "Bryan Adams",
  "Bryan Adams",
  "Phil Collins",
  "Duran Duran",
  "Duran Duran",
  "Paul Young",
  "Tears For Fears",
  "Tears For Fears",
  "Tears For Fears",
  "Huey Lewis",
  "Huey Lewis",
  "John Parr",
  "John Parr",
  "Dire Straits",
  "Dire Straits",
  "Dire Straits",
  "Ready For The World",
  "A-Ha",
  "Whitney Houston",
  "Stevie Wonder",
  "Jan Hammer",
  "Starship",
  "Starship",
  "Phil Collins/Marilyn Martin",
  "Mr. Mister",
  "Mr. Mister",
  "Lionel Richie",
  "Lionel Richie",


  "Lionel Richie",
  "Lionel Richie" ,
  "Dionne",
  "Dionne",
  "Dionne",
  "Dionne",
  "Whitney Houston",
  "Whitney Houston",
  "Mr. Mister",
  "Mr. Mister",
  "Starship",
  "Heart",
  "Falco" ,
  "Falco",
  "Falco",
  "Prince",
  "Prince",
  "Robert Palmer",
  "Pet Shop Boys",
  "Whitney Houston",
  "Whitney Houston",
  "Whitney Houston",
  "Madonna",
  "Patti LaBelle",
  "Patti LaBelle",
  "Patti LaBelle",
  "Billy Ocean",
  "Simply Red",
  "Genesis",
  "Peter Gabriel",
  "Peter Cetera",
  "Peter Cetera",
  "Madonna",
  "Madonna",
  "Steve Winwood",
  "Bananarama",
  "Berlin",
  "Huey Lewis",
  "Huey Lewis",
  "Huey Lewis",
  "Janet Jackson",
  "Janet Jackson",
  "Cyndi Lauper",
  "Cyndi Lauper",
  "Boston",
  "Boston",
  "The Human League",
  "Bon Jovi",
  "Peter Cetera",
  "Bruce Hornsby",
  "Bangles",
  "Bangles",


  "Bangles",
  "Bangles",
  "Gregory Abbott",
  "Billy Vera",
  "Billy Vera",
  "Madonna",
  "Bon Jovi",
  "Bon Jovi",
  "Bon Jovi",
  "Bon Jovi",
  "Huey Lewis",
  "Club Nouveau",
  "Club Nouveau",
  "Starship",
  "Starship",
  "Aretha Franklin",
  "Aretha Franklin",
  "Cutting Crew",
  "Cutting Crew",
  "U2",
  "U2",
  "U2",
  "Kim Wilde",
  "Atlantic Starr",
  "Lisa Lisa",
  "Whitney Houston",
  "Whitney Houston",
  "Heart",
  "Heart",
  "Heart",
  "Bob Seger",
  "U2",
  "U2",
  "Madonna",
  "Los Lobos",
  "Los Lobos",
  "Los Lobos",
  "Michael Jackson",
  "Whitney Houston",
  "Whitney Houston",
  "Whitesnake",
  "Lisa Lisa & Cult Jam",
  "Michael Jackson",
  "Michael Jackson",
  "Tiffany",
  "Tiffany",
  "Billy Idol",
  "Bill Medley",
  "Belinda Carlisle",
  "George Michael",
  "George Michael",
  "George Michael",
   "George Michael",
  "Whitney Houston",
  "George Harrison",
  "Michael Jackson",
  "INXS",
  "Tiffany",
  "Tiffany",
  "Expose",
  "George Michael",
  "George Michael",
  "Rick Astley",
  "Rick Astley",
  "Michael Jackson",
  "Michael Jackson",
  "Billy Ocean",
  "Billy Ocean",
  "Whitney Houston",
  "Whitney Houston",
  "Terence Trent D Arby",
  "Gloria Estefan",
  "Gloria Estefan",
  "George Michael",
  "George Michael",
  "George Michael",
  "Rick Astley",
  "Debbie Gibson",
  "Michael Jackson",
  "Cheap Trick",
  "Cheap Trick",
  "Richard Marx",
  "Steve Winwood",
  "Steve Winwood",
  "Steve Winwood",
  "Steve Winwood",
  "George Michael",
  "George Michael",
  "Guns N Roses",
  "Guns N Roses",
  "Bobby McFerrin",
  "Bobby McFerrin",
  "Def Leppard",
  "UB40",
  "Phil Collins",
  "Phil Collins",
  "The Beach Boys",
  "CThe Escape Club",
  "Bon Jovi",
  "Bon Jovi",
  "Will To Power",
  "Chicago",
  "Chicago",
  "Poison",
  "Poison",
   "Poison",
  "Bobby Brown",
  "Phil Collins",
  "Phil Collins",
  "Sheriff",
  "Paula Abdul",
  "Paula Abdul",
  "Paula Abdul",
  "Debbie Gibson",
  "Debbie Gibson",
  "Debbie Gibson",
  "Mike",
  "Bangles",
  "Roxette",
  "Fine Young Cannibals",
  "Madonna",
  "Madonna",
  "Madonna",
  "Bon Jovi",
  "Paula Abdul",
  "Paula Abdul",
  "Michael Damian",
  "Bette Midler",
  "New Kids On The Block",
  "Richard Marx",
  "Milli Vanilli",
  "Fine Young Cannibals",
  "Simply Red",
  "Martika",
  "Martika",
  "Prince",
  "Richard Marx",
  "Richard Marx",
  "Richard Marx",
  "Paula Abdul",
  "New Kids On The Block",
  "Gloria Estefan",
  "Milli Vanilli",
  "Milli Vanilli",
  "Janet Jackson",
  "Janet Jackson",
  "Janet Jackson",
  "Janet Jackson",
  "Roxette",
  "Bad English",
  "Bad English",
  "Milli Vanilli",
  "Milli Vanilli",
  "Billy Joel",
  "Billy Joel",
  "Phil Collins",
  "Phil Collins",
   "Phil Collins",
  "Phil Collins",
  "Michael Bolton",
  "Michael Bolton",
  "Michael Bolton",
  "Paula Abdul",
  "Paula Abdul",
  "Paula Abdul",
  "Janet Jackson",
  "Janet Jackson",
  "Janet Jackson",
  "Alannah Myles",
  "Alannah Myles",
  "Taylor Dayne",
  "Tommy Page",
  "Sinead O Connor",
  "Sinead O Connor",
  "Sinead O Connor",
  "Sinead O Connor",
  "Madonna",
  "Madonna",
  "Madonna",
  "Wilson Phillips",
  "Roxette",
  "Roxette",
  "New Kids On The Block",
  "New Kids On The Block",
  "New Kids On The Block",
  "Glenn Medeiros",
  "Glenn Medeiros",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Sweet Sensation",
  "Jon Bon Jovi",
  "Wilson Phillips",
  "Wilson Phillips",
  "Nelson",
  "Maxi Priest",
  "George Michael",
  "James Ingram",
  "Janet Jackson",
  "Vanilla Ice",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Whitney Houston",
  "Stevie B",
  "Stevie B",
  "Stevie B",
  "Stevie B",
  "Madonna",
  "Madonna",
  "Janet Jackson",
  "Surface",
  "Surface",
  "C+C Music Factory",
  "C+C Music Factory",
  "Whitney Houston",
  "Whitney Houston",
  "Mariah Carey",
  "Mariah Carey",
  "Timmy T.",
  "Gloria Estefan",
  "Gloria Estefan",
  "London Beat",
  "Wilson Phillips",
  "Amy Grant",
  "Amy Grant",
  "Roxette",
  "Hi-Five",
  "Mariah Carey",
  "Mariah Carey",
  "Extreme",
  "Paula Abdul",
  "Paula Abdul",
  "Paula Abdul",
  "Paula Abdul",
  "Paula Abdul",
  "EMF",
  "Bryan Adams",
  "Bryan Adams",
  "Bryan Adams",
  "Bryan Adams",
  "Bryan Adams",
  "Bryan Adams",
  "Bryan Adams",
  "Paula Abdul",
  "Color Me Badd",
  "Color Me Badd",
  "Marky Mark",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Karyn White",
  "Prince And The N.P.G.",
  "Prince And The N.P.G.",
  "Michael Bolton",
  "P.M. Dawn",
  "Michael Jackson",
  "Michael Jackson",
  "Michael Jackson",
  "Michael Jackson",
  
  "Michael Jackson",
  "Michael Jackson",
  "Michael Jackson",
  "Color Me Bad",
  "George Michael/Elton John",
  "Right Said Fred",
  "Right Said Fred",
  "Right Said Fred",
  "Mr.Big",
  "Mr.Big",
  "Mr.Big",
  "Vanessa Williams",
  "Vanessa Williams",
  "Vanessa Williams",
  "Vanessa Williams",
  "Vanessa Williams",
  "Kris Kross",
  "Kris Kross",
  "Kris Kross",
  "Kris Kross",
  "Kris Kross",
  "Kris Kross",
  "Kris Kross",
  "Kris Kross",
  "Mariah Carey",
  "Mariah Carey",
  "Sir Mix-A-Lot",
  "Sir Mix-A-Lot",
  "Sir Mix-A-Lot",
  "Sir Mix-A-Lot",
  "Sir Mix-A-Lot",
  "Madonna",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "The Heights",
  "The Heights",
  "Whitney Houston",
  "Whitney Houston",
  "Whitney Houston",
  "Whitney Houston",
  "Whitney Houston",
  "Whitney Houston",
  "Whitney Houston",
  "Whitney Houston",
  "Whitney Houston",
  "Whitney Houston",
  "Whitney Houston",
  "Whitney Houston",
  "Whitney Houston",
  "Whitney Houston",
  "Peabo Bryson",
  "Snow",
  "Snow",
  "Snow",
  "Snow",
  "Snow",
  "Snow",
  "Snow",
  "Silk",
  "Silk",
  "Janet Jackson",
  "Janet Jackson",
  "Janet Jackson",
  "Janet Jackson",
  "Janet Jackson",
  "Janet Jackson",
  "Janet Jackson",
  "Janet Jackson",
  "SWV",
  "SWV",
  "UB40",
  "UB40",
  "UB40",
  "UB40",
  "UB40",
  "UB40",
  "UB40",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Meat Loaf",
  "Meat Loaf",
  "Meat Loaf",
  "Meat Loaf",
  "Meat Loaf",
  "Janet Jackson",
  "Janet Jackson",
  "Mariah Carey",
  
  //1994
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Bryan Adams/Rod Stewart/Sting",
  "Bryan Adams/Rod Stewart/Sting",
  "Bryan Adams/Rod Stewart/Sting",
  "Celine Dion",
  "Celine Dion",
  "Celine Dion",
  "Celine Dion",
  "Ace Of Base",
  "Ace Of Base",
  "Ace Of Base",
  "Ace Of Base",
  "R. Kelly",
  "R. Kelly",
  "R. Kelly",
  "R. Kelly",
  "Ace Of Base",
  "Ace Of Base",
  "All-4-One",
  "All-4-One",
  "All-4-One",
  "All-4-One",
  "All-4-One",
  "All-4-One",
  "All-4-One",
  "All-4-One",
  "All-4-One",
  "All-4-One",
  "All-4-One",
  "Lisa Loeb",
  "Lisa Loeb",
  "Lisa Loeb",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "Ini Kamoze",
  "Ini Kamoze",
  "Boyz II Men",
  
  //1995
  "Boyz II Men",
  "Boyz II Men",
  "Boyz II Men",
  "TLC",
  "TLC",
  "TLC",
  "TLC",
  "Madonna",
  "Madonna",
  "Madonna",
  "Madonna",
  "Madonna",
  "Madonna",
  "Madonna",
  "Montell Jordan",
  "Montell Jordan",
  "Montell Jordan",
  "Montell Jordan",
  "Montell Jordan",
  "Montell Jordan",
  "Montell Jordan",
  "Bryan Adams",
  "Bryan Adams",
  "Bryan Adams",
  "Bryan Adams",
  "Bryan Adams",
  "TLC",
  "TLC",
  "TLC",
  "TLC",
  "TLC",
  "TLC",
  "TLC",
  "Seal",
  "Michael Jackson",
  "Coolio",
  "Coolio",
  "Coolio",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Whitney Houston",
  "Mariah Carey & Boyz II Men",
  "Mariah Carey & Boyz II Men",
  "Mariah Carey & Boyz II Men",
  "Mariah Carey & Boyz II Men",
  "Mariah Carey & Boyz II Men",
  
  //1996
  "Mariah Carey & Boyz II Men",
  "Mariah Carey & Boyz II Men",
  "Mariah Carey & Boyz II Men",
  "Mariah Carey & Boyz II Men",
  "Mariah Carey & Boyz II Men",
  "Mariah Carey & Boyz II Men",
  "Mariah Carey & Boyz II Men",
  "Mariah Carey & Boyz II Men",
  "Mariah Carey & Boyz II Men",
  "Mariah Carey & Boyz II Men",
  "Mariah Carey & Boyz II Men",
  "Celine Dion",
  "Celine Dion",
  "Celine Dion",
  "Celine Dion",
  "Celine Dion",
  "Celine Dion",
  "Mariah Carey",
  "Mariah Carey",
  "Bone Thugs-N-Harmony",
  "Bone Thugs-N-Harmony",
  "Bone Thugs-N-Harmony",
  "Bone Thugs-N-Harmony",
  "Bone Thugs-N-Harmony",
  "Bone Thugs-N-Harmony",
  "Bone Thugs-N-Harmony",
  "Bone Thugs-N-Harmony",
  "2Pac",
  "2Pac",
  "Toni Braxton",
  "Los Del Rio",
  "Los Del Rio",
  "Los Del Rio",
  "Los Del Rio",
  "Los Del Rio",
  "Los Del Rio",
  "Los Del Rio",
  "Los Del Rio",
  "Los Del Rio",
  "Los Del Rio",
  "Los Del Rio",
  "Los Del Rio",
  "Los Del Rio",
  "Los Del Rio",
  "BLACKstreet",
  "BLACKstreet",
  "BLACKstreet",
  "BLACKstreet",
  "Toni Braxton",
  "Toni Braxton",
  "Toni Braxton",
  "Toni Braxton",
  
  //1997
  "Toni Braxton",
  "Toni Braxton",
  "Toni Braxton",
  "Toni Braxton",
  "Toni Braxton",
  "Toni Braxton",
  "Toni Braxton",
  "Spice Girls",
  "Spice Girls",
  "Spice Girls",
  "Spice Girls",
  "Puff Daddy",
  "Puff Daddy",
  "Puff Daddy",
  "Puff Daddy",
  "Puff Daddy",
  "Puff Daddy",
  "The Notorious B.I.G.",
  "The Notorious B.I.G.",
  "The Notorious B.I.G.",
  "Hanson",
  "Hanson",
  "Hanson",
  "Puff Daddy",
  "Puff Daddy",
  "Puff Daddy",
  "Puff Daddy",
  "Puff Daddy",
  "Puff Daddy",
  "Puff Daddy",
  "Puff Daddy",
  "Puff Daddy",
  "Puff Daddy",
  "Puff Daddy",
  "The Notorious B.I.G.",
  "The Notorious B.I.G.",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Boyz II Men",
  "Elton John",
  "Elton John",
  "Elton John",
  "Elton John",
  "Elton John",
  "Elton John",
  "Elton John",
  "Elton John",
  "Elton John",
  "Elton John",
  "Elton John",
  "Elton John",
  
  //1998
  "Elton John",
  "Elton John",
  "Savage Garden",
  "Savage Garden",
  "Janet",
  "Janet",
  "Usher",
  "Usher",
  "Celine Dion",
  "Celine Dion",
  "Will Smith",
  "Will Smith",
  "Will Smith",
  "K-Ci",
  "K-Ci",
  "K-Ci",
  "Next",
  "Next",
  "Next",
  "Next",
  "Mariah Carey",
  "Next",
  "Brandy",
  "Brandy",
  "Brandy",
  "Brandy",
  "Brandy",
  "Brandy",
  "Brandy",
  "Brandy",
  "Brandy",
  "Brandy",
  "Brandy & Monica",
  "Brandy",
  "Brandy",
  "Aerosmith",
  "Aerosmith",
  "Aerosmith",
  "Aerosmith",
  "Monica",
  "Monica",
  "Monica",
  "Lauryn Hill",
  "Lauryn Hill",
  "Divine",
  "R.Kelly",
  "R.Kelly",
  "R.Kelly",
  "R.Kelly",
  
  //1999
  "R.Kelly",
  "R.Kelly",
  "Brandy",
  "Brandy",
  "Britney Spears",
  "Britney Spears",
  "Monica",
  "Monica",
  "Monica",
  "Monica",
  "Cher",
  "Cher",
  "Cher",
  "Cher",
  "TLC",
  "TLC",
  "TLC",
  "TLC",
  "Ricky Martin",
  "Ricky Martin",
  "Ricky Martin",
  "Ricky Martin",
  "Ricky Martin",
  "Jennifer Lopez",
  "Jennifer Lopez",
  "Jennifer Lopez",
  "Jennifer Lopez",
  "Jennifer Lopez",
  "Destiny's Child",
  "Will Smith",
  "Christina Aguilera",
  "Christina Aguilera",
  "Christina Aguilera",
  "Christina Aguilera",
  "Christina Aguilera",
  "Enrique Iglesias",
  "Enrique Iglesias",
  "TLC",
  "TLC",
  "TLC",
  "Mariah Carey",
  "Mariah Carey",
  "Santana",
  "Santana",
  "Santana",
  "Santana",
  "Santana",
  "Santana",
  "Santana",
  "Santana",
  "Santana",
  "Santana",
  
  //2000
  "Santana",
  "Santana",
  "Christina Aguilera",
  "Christina Aguilera",
  "Savage Garden",
  "Savage Garden",
  "Savage Garden",
  "Mariah Carey",
  "Savage Garden",
  "Lonestar",
  "Lonestar",
  "Destiny's Child",
  "Destiny's Child",
  "Destiny's Child",
  "Santana",
  "Santana",
  "Santana",
  "Santana",
  "Santana",
  "Santana",
  "Santana",
  "Santana",
  "Santana",
  "Santana",
  "Aaliyah",
  "Enrique Iglesias",
  "Enrique Iglesias",
  "Enrique Iglesias",
  "Vertical Horizon",
  "Matchbox Twenty",
  "N Sync",
  "N Sync",
  "Sisqo",
  "Sisqo",
  "Janet",
  "Janet",
  "Janet",
  "Madonna",
  "Madonna",
  "Madonna",
  "Madonna",
  "Christina Aguilera",
  "Christina Aguilera",
  "Christina Aguilera",
  "Christina Aguilera",
  "Creed",
  "Destiny's Child",
  "Destiny's Child",
  "Destiny's Child",
  "Destiny's Child",
  "Destiny's Child",
  "Destiny's Child",
  "Destiny's Child",
  
  //2001
  "Destiny's Child",
  "Destiny's Child",
  "Destiny's Child",
  "Destiny's Child",
  "Shaggy",
  "Shaggy",
  "OutKast",
  "Joe",
  "Joe",
  "Joe",
  "Joe",
  "Crazy Town",
  "Janet",
  "Janet",
  "Janet",
  "Janet",
  "Janet",
  "Janet",
  "Janet",
  "Christina Aguilera",
  "Christina Aguilera",
  "Christina Aguilera",
  "Christina Aguilera",
  "Christina Aguilera",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Destiny's Child",
  "Destiny's Child",
  "Alicia Keys",
  "Alicia Keys",
  "Alicia Keys",
  "Jennifer Lopez",
  "Jennifer Lopez",
  "Jennifer Lopez",
  "Mary J. Blige",
  "Mary J. Blige",
  "Mary J. Blige",
  "Mary J. Blige",
  "Mary J. Blige",
  "Mary J. Blige",
  "Usher",
  "Nickelback",
  "Nickelback",
  
  //2002
  "Nickelback",
  "Nickelback",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Ja Rule",
  "Ja Rule",
  "Jennifer",
  "Jennifer",
  "Jennifer",
  "Jennifer",
  "Jennifer",
  "Jennifer",
  "Ashanti",
  "Ashanti",
  "Ashanti",
  "Ashanti",
  "Ashanti",
  "Ashanti",
  "Ashanti",
  "Ashanti",
  "Ashanti",
  "Ashanti",
  "Nelly",
  "Nelly",
  "Nelly",
  "Nelly",
  "Nelly",
  "Nelly",
  "Nelly",
  "Nelly",
  "Nelly",
  "Nelly",
  "Nelly",
  "Nelly",
  "Nelly",
  "Nelly",
  "Kelly Clarkson",
  "Kelly Clarkson",
  "Nelly",
  "Nelly",
  "Nelly",
  "Eminem",
  "Eminem",
  "Eminem",
  "Eminem",
  "Eminem",
  "Eminem",
  "Eminem",
  "Eminem",
  
  //2003
  "Eminem",
  "Eminem",
  "Eminem",
  "Eminem",
  "B2K & P. Diddy",
  "Jennifer Lopez",
  "Jennifer Lopez",
  "Jennifer Lopez",
  "Jennifer Lopez",
  "50 Cent",
  "50 Cent",
  "50 Cent",
  "50 Cent",
  "50 Cent",
  "50 Cent",
  "50 Cent",
  "50 Cent",
  "50 Cent",
  "Sean Paul",
  "Sean Paul",
  "Sean Paul",
  "50 Cent",
  "50 Cent",
  "50 Cent",
  "50 Cent",
  "Clay Aiken",
  "Clay Aiken",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Nelly",
  "Nelly",
  "Nelly",
  "Nelly",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Ludacris",
  "OutKast",
  "OutKast",
  "OutKast",
  
  //2004
  "OutKast",
  "OutKast",
  "OutKast",
  "OutKast",
  "OutKast",
  "OutKast",
  "OutKast",
  "Twista",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Fantasia",
  "Usher",
  "Usher",
  "Usher",
  "Juvenile",
  "Juvenile",
  "Terror Squad",
  "Terror Squad",
  "Terror Squad",
  "Ciara",
  "Ciara",
  "Ciara",
  "Ciara",
  "Ciara",
  "Ciara",
  "Ciara",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Usher",
  "Snoop Dogg",
  "Snoop Dogg",
  "Snoop Dogg",
  
  //2005
  "Mario",
  "Mario",
  "Mario",
  "Mario",
  "Mario",
  "Mario",
  "Mario",
  "Mario",
  "Mario",
  "50 Cent",
  "50 Cent",
  "50 Cent",
  "50 Cent",
  "50 Cent",
  "50 Cent",
  "50 Cent",
  "50 Cent",
  "50 Cent",
  "Gwen Stefani",
  "Gwen Stefani",
  "Gwen Stefani",
  "Gwen Stefani",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Inside Your Heaven",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Mariah Carey",
  "Kanye West",
  "Kanye West",
  "Kanye West",
  "Kanye West",
  "Kanye West",
  "Kanye West",
  "Kanye West",
  "Kanye West",
  "Kanye West",
  "Kanye West",
  "Chris Brown",
  "Chris Brown",
  "Chris Brown",
  "Chris Brown",
  "Chris Brown",
  "Mariah Carey",
  
  //2006
  "Mariah Carey",
  "D4L",
  "Nelly",
  "Nelly",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "James Blunt",
  "Ne-Yo",
  "Ne-Yo",
  "Sean Paul",
  "Daniel Powter",
  "Daniel Powter",
  "Daniel Powter",
  "Daniel Powter",
  "Daniel Powter",
  "Rihanna",
  "Rihanna",
  "Rihanna",
  "Chamillionaire",
  "Chamillionaire",
  "Shakira",
  "Shakira",
  "Taylor Hicks",
  "Nelly Furtado",
  "Nelly Furtado",
  "Nelly Furtado",
  "Nelly Furtado",
  "Nelly Furtado",
  "Nelly Furtado",
  "Fergie",
  "Fergie",
  "Justin Timberlake",
  "Justin Timberlake",
  "Justin Timberlake",
  "Justin Timberlake",
  "Justin Timberlake",
  "Justin Timberlake",
  "Justin Timberlake",
  "Ludacris",
  "Ludacris",
  "Justin Timberlake",
  "Justin Timberlake",
  "Justin Timberlake",
  "Akon",
  "Akon",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  
  //2007
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Beyonce",
  "Nelly Furtado",
  "Justin Timberlake",
  "Justin Timberlake",
  "Mims",
  "Mims",
  "Fergie",
  "Fergie",
  "Akon",
  "Akon",
  "Timbaland",
  "Timbaland",
  "Avril Lavigne",
  "Maroon 5",
  "Maroon 5",
  "T-Pain",
  "Maroon 5",
  "Rihanna",
  "Rihanna",
  "Rihanna",
  "Rihanna",
  "Rihanna",
  "Rihanna",
  "Rihanna",
  "Plain White T's",
  "Plain White T's",
  "Sean Kingston",
  "Sean Kingston",
  "Sean Kingston",
  "Sean Kingston",
  "Fergie",
  "Soulja Boy",
  "Soulja Boy",
  "Kanye West",
  "Soulja Boy",
  "Soulja Boy",
  "Soulja Boy",
  "Soulja Boy",
  "Soulja Boy",
  "Chris Brown",
  "Chris Brown",
  "Chris Brown",
  "Alicia Keys",
  "Alicia Keys",
  "Alicia Keys",
  "Alicia Keys",
  "Alicia Keys",
  
  //2008
  "Flo Rida",
  "Flo Rida",
  "Flo Rida",
  "Flo Rida",
  "Flo Rida",
  "Flo Rida",
  "Flo Rida",
  "Flo Rida",
  "Flo Rida",
  "Flo Rida",
  "Usher",
  "Usher",
  "Usher",
  "Leona lewis",
  "Mariah Carey",
  "Mariah Carey",
  "Leona Lewis",
  "Lil Wayne",
  "Leona Lewis",
  "Leona Lewis",
  "Rihanna",
  "Lil Wayne",
  "Lil Wayne",
  "Lil Wayne",
  "Lil Wayne",
  "Coldplay",
  "Katy Perry",
  "Katy Perry",
  "Katy Perry",
  "Katy Perry",
  "Katy Perry",
  "Katy Perry",
  "Katy Perry",
  "Rihanna",
  "Rihanna",
  "T.I.",
  "T.I.",
  "T.I.",
  "Pink",
  "T.I.",
  "T.I.",
  "T.I.",
  "Britney Spears",
  "T.I.",
  "T.I.",
  "T.I.",
  "T.I.",
  "T.I.",
  "Beyonce",
  "T.I.",
  "Beyonce",
  
  //2009
  "Beyonce",
  "Beyonce",
  "Lady GaGa",
  "Lady GaGa",
  "Lady GaGa",
  "Kelly Clarkson",
  "Kelly Clarkson",
  "Eminem, Dr. Dre & 50 Cent",
  "Flo Rida",
  "Flo Rida",
  "Flo Rida",
  "Flo Rida",
  "Flo Rida",
  "Flo Rida",
  "Lady Gaga",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "Jay Sean",
  "Britney Spears",
  "Jay Sean",
  "Owl City",
  "Jason DeRulo",
  "Owl City",
  "Jay-Z + Alicia Keys",
  "Jay-Z + Alicia Keys",
  "Jay-Z + Alicia Keys",
  "Jay-Z + Alicia Keys",
  "Jay-Z + Alicia Keys",
  
  //2010
  "Ke$ha",
  "Ke$ha",
  "Ke$ha",
  "Ke$ha",
  "Ke$ha",
  "Ke$ha",
  "Ke$ha",
  "Ke$ha",
  "Ke$ha",
  "The Black Eyed Peas",
  "The Black Eyed Peas",
  "Taio Cruz",
  "Rihanna",
  "Rihanna",
  "Rihanna",
  "Rihanna",
  "Rihanna",
  "B.o.B",
  "B.o.B",
  "Usher",
  "Eminem",
  "Usher",
  "Usher",
  "Usher",
  "Katy Perry",
  "Katy Perry",
  "Katy Perry",
  "Katy Perry",
  "Katy Perry",
  "Katy Perry",
  "Eminem",
  "Eminem",
  "Eminem",
  "Eminem",
  "Eminem",
  "Eminem",
  "Eminem",
  "Katy Perry",
  "Katy Perry",
  "Bruno Mars",
  "Bruno Mars",
  "Bruno Mars",
  "Bruno Mars",
  "Far*East Movement",
  "Far*East Movement",
  "Ke$ha",
  "Rihanna Featuring Drake",
  "Far*East Movement",
  "Rihanna",
  "Pink",
  "Katy Perry",
  "Katy Perry",
  
  //2011
  "Katy Perry",
  "Bruno Mars",
  "Katy Perry",
  "Bruno Mars",
  "Britney Spears",
  "Bruno Mars",
  "Bruno Mars",
  "Wiz Khalifa",
  "Lady Gaga",
  "Lady Gaga",
  "Lady Gaga",
  "Lady Gaga",
  "Lady Gaga",
  "Lady Gaga",
  "Katy Perry",
  "Katy Perry",
  "Katy Perry",
  "Rihanna",
  "Katy Perry",
  "Katy Perry",
  "Adele",
  "Adele",
  "Adele",
  "Adele",
  "Adele",
  "Adele",
  "Adele",
  "Pitbull",
  "LMFAO",
  "LMFAO",
  "LMFAO",
  "LMFAO",
  "LMFAO",
  "LMFAO",
  "Katy Perry",
  "Katy Perry",
  "Maroon 5",
  "Adele",
  "Maroon 5",
  "Maroon 5",
  "Maroon 5",
  "Adele",
  "Adele",
  "Adele",
  "Adele",
  "Rihanna",
  "Rihanna",
  "Rihanna",
  "Rihanna",
  "Rihanna",
  "Rihanna",
  "Rihanna",
  "Rihanna",
  
  //2012
  "LMFAO",
  "LMFAO",
  "Rihanna",
  "Rihanna",
  "Adele",
  "Adele",
  "Kelly Clarkson",
  "Kelly Clarkson",
  "Katy Perry",
  "Kelly Clarkson",
  "fun.",
  "fun.",
  "fun.",
  "fun.",
  "fun.",
  "fun.",
  "Gotye",
  "Gotye",
  "Gotye",
  "Gotye",
  "Gotye",
  "Gotye",
  "Gotye",
  "Gotye",
  "Carly Rae Jepsen",
  "Carly Rae Jepsen",
  "Carly Rae Jepsen",
  "Carly Rae Jepsen",
  "Carly Rae Jepsen",
  "Carly Rae Jepsen",
  "Carly Rae Jepsen",
  "Carly Rae Jepsen",
  "Carly Rae Jepsen",
  "Flo Rida",
  "Taylor Swift",
  "Taylor Swift",
  "Flo Rida",
  "Taylor Swift",
  "Maroon 5",
  "Maroon 5",
  "Maroon 5",
  "Maroon 5",
  "Maroon 5",
  "Maroon 5",
  "Maroon 5",
  "Maroon 5",
  "Maroon 5",
  "Rihanna",
  "Rihanna",
  "Rihanna",
  "Bruno Mars",
  "Bruno Mars",
  
  //2013
  "Bruno Mars",
  "Bruno Mars",
  "Bruno Mars",
  "Bruno Mars",
  "Macklemore & Ryan Lewis",
  "Macklemore & Ryan Lewis",
  "Macklemore & Ryan Lewis",
  "Macklemore & Ryan Lewis",
  "Baauer",
  "Baauer",
  "Baauer",
  "Baauer",
  "Baauer",
  "Macklemore & Ryan Lewis",
  "Macklemore & Ryan Lewis",
  "Bruno Mars",
  "P!nk Featuring Nate Ruess",
  "P!nk Featuring Nate Ruess",
  "P!nk Featuring Nate Ruess",
  "Macklemore & Ryan Lewis",
  "Macklemore & Ryan Lewis",
  "Macklemore & Ryan Lewis",
  "Macklemore & Ryan Lewis",
  "Macklemore & Ryan Lewis",
  "Robin Thicke",
  "Robin Thicke",
  "Robin Thicke",
  "Robin Thicke",
  "Robin Thicke",
  "Robin Thicke",
  "Robin Thicke",
  "Robin Thicke",
  "Robin Thicke",
  "Robin Thicke",
  "Robin Thicke",
  "Robin Thicke",
  "Katy Perry",
  "Katy Perry",
  "Miley Cyrus",
  "Miley Cyrus",
  "Lorde",
  "Lorde",
  "Lorde",
  "Lorde",
  "Lorde",
  "Lorde",
  "Lorde",
  "Lorde",
  "Lorde",
  "Miley Cyrus",
  "Eminem",
  "Eminem",
  
  //2014
  "Eminem",
  "Eminem",
  "Pitbull",
  "Pitbull",
  "Pitbull",
  "Katy Perry",
  "Katy Perry",
  "Katy Perry",
  "Katy Perry",
  "Pharrell Williams",
  "Pharrell Williams",
  "Pharrell Williams",
  "Pharrell Williams",
  "Pharrell Williams",
  "Pharrell Williams",
  "Pharrell Williams",
  "Pharrell Williams",
  "Pharrell Williams",
  "Pharrell Williams",
  "John Legend",
  "John Legend",
  "John Legend",
  "Iggy Azalea",
  "Iggy Azalea",
  "Iggy Azalea",
  "Iggy Azalea",
  "Iggy Azalea",
  "Iggy Azalea",
  "Iggy Azalea",
  "MAGIC!",
  "MAGIC!",
  "MAGIC!",
  "MAGIC!",
  "MAGIC!",
  "MAGIC!",
  "Taylor Swift",
  "Taylor Swift",
  "Meghan Trainor",
  "Meghan Trainor",
  "Meghan Trainor",
  "Meghan Trainor",
  "Meghan Trainor",
  "Meghan Trainor",
  "Meghan Trainor",
  "Meghan Trainor",
  "Taylor Swift",
  "Taylor Swift",
  "Taylor Swift",
  "Taylor Swift",
  "Taylor Swift",
  "Taylor Swift",
  "Taylor Swift",
  
  //2015
  "Taylor Swift",
  "Taylor Swift",
  "Mark Ronson",
  "Mark Ronson",
  "Mark Ronson",
  "Mark Ronson",
  "Mark Ronson",
  "Mark Ronson",
  "Mark Ronson",
  "Mark Ronson",
  "Mark Ronson",
  "Mark Ronson",
  "Mark Ronson",
  "Mark Ronson",
  "Mark Ronson",
  "Mark Ronson",
  "Wiz Khalifa",
  "Wiz Khalifa",
  "Wiz Khalifa",
  "Wiz Khalifa",
  "Wiz Khalifa",
  "Wiz Khalifa",
  "Taylor Swift",
  "Wiz Khalifa",
  "Wiz Khalifa",
  "Wiz Khalifa",
  "Wiz Khalifa",
  "Wiz Khalifa",
  "Wiz Khalifa",
  "OMI",
  "OMI",
  "OMI",
  "OMI",
  "The Weeknd",
  "OMI",
  "OMI",
  "The Weeknd",
  "Justin Bieber",
  "The Weeknd",
  "The Weeknd",
  "The Weeknd",
  "The Weeknd",
  "The Weeknd",
  "The Weeknd",
  "The Weeknd",
  "Adele",
  "Adele",
  "Adele",
  "Adele",
  "Adele",
  "Adele",
  "Adele",


];



  


